---
name: Publish

on:
  push:
    branches:
      - 'release-*'
      - 'main'
    tags:
      - 'v*.*.*'

env:
  FORCE_COLOR: true
  REGISTRY: quay.io
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  publish:
    name: OCI Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - uses: davidB/rust-cargo-make@v1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge upstream
        if: github.event_name == 'pull_request'
        run: |
          if ! git config user.name > /dev/null; then
            git config user.name "John Doe"
          fi
          if ! git config user.email > /dev/null; then
            git config user.email "johndoe@localhost"
          fi
          git remote add upstream https://github.com/${{ github.repository }}.git
          git pull --no-rebase upstream ${{ github.base_ref }}
        shell: bash

      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        if: ${{ env.REGISTRY_PASSWORD != '' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Publish
        if: ${{ env.REGISTRY_PASSWORD != '' }}
        run: cargo make publish
